### PR TITLE
Better Avatar Preview Server

### PR DESCRIPTION
**Pull request by SirOMGitsYOU**
Does what it says on the tin, just simply improves on the avatar container changing the server URL from crafatar to mc-heads which retaining the same outcome but better as this now includes the characters hat layer.

### CODE REVIEW

**Comment by dscalzi** [comment]
Is there a specific benefit of using this website over crafatar? I believe you can show the helmet on crafatar by just adding a url parameter https://crafatar.com/#meta-parameters

**Comment by SirOMGitsYOU** [comment]
> Is there a specific benefit of using this website over crafatar? I believe you can show the helmet on crafatar by just adding a url parameter https://crafatar.com/#meta-parameters

Yeah I tried getting that to work on my instance not sure what I did wrong but it was not having any of it couldn't get it to display the hat layer, I have always used mc-heads as I just find it to be easier to use and never had any issues with it, it's what i use for heads/player models on my store page just thought it was a better option than crafatar.

**Comment by dscalzi** [comment]
Can you change the other usages of crafatar to mc-heads? Just search the project and you'll find them.

**Comment by SirOMGitsYOU** [comment]
I Have updated the remaining URLs.

**Review by dscalzi — APPROVED** [review]

**Pull request merged**
