### PR TITLE
Removed Mojang login

### PR DESCRIPTION
**Pull request by nullure**
Removed Mojang login since works no longer

### CODE REVIEW

**Comment by gamernitro999** [comment]
mojang shouldn't be removed it's used for legacy account

**Comment by Nightmaregodss** [comment]
there are a lot of problems with Mojang login + we can use alt accounts + Mojang don't likes to promote there login in Minecraft anymore

**Comment by gamernitro999** [comment]
what are the problems with mojang login ? what is the problem with alt (you can ban their ip on your server) ? and mojang don't promote their login system because if you have a mojang account you need to migrate.
but deleting the mojang login would mean that legacy account won't be able to connect and play because they cant migrate to microsoft account and can only login through mojang's login system

**Comment by GeekCornerGH** [comment]
There is no point in removing this for the moment, legacy accounts still a thing and I guess some Mojang accounts doesn't have the migration requirement for now

**Comment by dscalzi** [comment]
not doing this at the moment

**Pull request closed without merging**
