### PR TITLE
Fixes related to updates

### PR DESCRIPTION
**Pull request by tanetakumi**
I want an update system and made a few modifications. However, it is not complete.
Sorry, I can't understand the update method in ”populateSettingsUpdateInformation”. And also, I don't know how to judge arm64.dmg and x64.dmg.

### CODE REVIEW

**Comment by gamernitro999** [comment]
there is already an autoupdate system that work perfectly and yours only work with this repo and is not made so that everyone can use it for their forks

**Comment by tanetakumi** [comment]
> there is already an autoupdate system that work perfectly and yours only work with this repo and is not made so that everyone can use it for their forks

Thanks for letting me know.
```gamernitro999/gh-HeliosReleaseAutomate```
Is this the automatic update tool?

**Comment by tanetakumi** [comment]
> > Can we use it?
> 
> what is "it" ?

Sorry, Can we use an auto update system?

**Comment by tanetakumi** [comment]
Sorry for my lack of knowledge.
I was able to use this system with ```dev-app-update.yml```.

**Pull request closed without merging**
