### PR TITLE
Feature/1.17

### PR DESCRIPTION
**Pull request by GekoXD**
mm

### CODE REVIEW

**Comment by sjempotje** [comment]
You want to merge the 1.17+ feature with the master, why?

**Comment by gamernitro999** [comment]
> You want to merge the 1.17+ feature with the master, why?

in order to have one launcher that support both pre 1.17 and post 1.17

**Comment by gamernitro999** [comment]
I still don't think that the 1.17 branch is ready to be merged

**Comment by sjempotje** [comment]
Yeah I meant that, forgot to add that lol

**Comment by dscalzi** [comment]
branch is not ready

**Pull request closed without merging**
