### PR TITLE
MLS

### PR DESCRIPTION
**Pull request by norhu1130**
BY Kurmper

Microsoft Login Support
MLS

### CODE REVIEW

**Review by qqtq — CHANGES_REQUESTED** [review]
Client ID needs to be changed in index.js and microsoft.js

**Review by Superkooka — APPROVED** [review]

**Comment by DrDeee** [comment]
In authmanager the function `validateSelected()` does not work properly yet. If an account token is still valid, nothing is returned.

```diff
exports.validateSelected = async function () {
    const current = ConfigManager.getSelectedAccount()
    const isValid = await Mojang.validate(current.accessToken, ConfigManager.getClientToken())
    if (!isValid) {
        try {
            if (ConfigManager.getSelectedAccount() === 'microsoft') {
                const validate = await validateSelectedMicrosoft()
                return validate
            } else {
                const validate = await validateSelectedMojang()
                return validate
            }
        } catch (error) {
            return Promise.reject(error)
        }
--- }
+++ } else return true
}
```

**Comment by Asuniia** [comment]
Hello ! 

I Have a 401 error after close microsoft pop-up..
image

**Comment by norhu1130** [comment]
Unfortunately, I saw the bug happen,
I deleted the repo. I can't fix it.
I'm sorry.

**Comment by DrDeee** [comment]
I've the code a little bit modified (better error handling, german translations & other styles) in my fork, but I can't create a pull request directly, so I'll extract the changes and remove translations to create a new pull request.

**Comment by norhu1130** [comment]
#143

**Comment by dscalzi** [comment]
For historical purposes:

Thanks everyone, official support will be coming through this PR #216

Relevant links:
- #216 - Official Solution
- #135 - Microsoft Auth PR by @norhu1130
- #143 - Microsoft Auth PR by @DrDeee 
- #186 - Refactor of @DrDeee's PR by @Richienb

**Pull request closed without merging**
