### PR TITLE
Create de_DE.json

### PR DESCRIPTION
**Pull request by lukruh**
no clue how useful this is at the current stage of language support, but this is how I'd translate the strings for my german version of the launcher.

### CODE REVIEW

**Review by davidmayr — CHANGES_REQUESTED** [review]
anzumeldenas should be anzumelden in "userMigrated"
in ratelimit desc "Zeit.Bitte " should be "Zeit. Bitte "

you can also improve not paid to:
"desc": "Der Account mit dem du dich anmelden möchtest verfügt über keine gültige Minecraftversion.<br>Du kannst das Spiel auf <a href=\"https://minecraft.net/\">Minecraft.net</a> kaufen"

**Comment by MenschenToaster** [comment]
Also "keine gültige Minecraftversion" should be "keine gültige Minecraft-Version"

**Comment by dscalzi** [comment]
The language system on v1 is not completely implemented. Deferring for v2, feel free to keep a discussion going though.

**Comment by lukruh** [comment]
Thanks I'll add your additions to the PR, but for now I'm waiting for the next major release. As far as I understood the customization and language file implementation will be reworked.

**Comment by dscalzi** [comment]
Multi-language was never fully implemented and will be phased out. It is awful to maintain without a serious collective effort.

**Pull request closed without merging**
