### PR TITLE
Test Mode

### PR DESCRIPTION
**Pull request by e042**
This PR adds a **test mode** to the Helios Launcher. 
If this is activated, not the default distribution is loaded, but another one (specified in the distromanager).
You can enable/disable the test mode via the console:
```javascript
ConfigManager.setTesting(true)
ConfigManager.setTesting(false)

ConfigManager.isTesting() // is in test mode
```

---

*DrDeee*

### CODE REVIEW

**Comment by jordanamr** [comment]
What's the point when we already have the debug distro ?

**Comment by DrDeee** [comment]
And were can I set the debug distro, @jordanamr ?

**Comment by jordanamr** [comment]
Please see the source code.

**Comment by dscalzi** [comment]
There is an option to use a local distribution.

1. On Nebula - `npm run start -- g distro dev_distribution --installLocal`
2. In helios - Open devtools. Execute:
  - DistroManager.setDevMode(true)
  - DistroManager.pullLocal()

More details: https://github.com/dscalzi/HeliosLauncher/wiki/Developer-Mode
  
I'll leave this open for now because its an option to pull from a remote "debug" distribution, which may be useful.

**Pull request closed without merging**
