### PR TITLE
fix: Mojang's Status is broken

### PR DESCRIPTION
**Pull request by GeekCornerGH**
Hello @dscalzi, I made this Pull Request to fix Mojang services. Acording to [this tweet](https://twitter.com/Mojang_Ined/status/1445302015706415104), they removed the status server. I wrote a fix to this, so status still acurate.

# How does it works:
I used [Upptime](https://upptime.js.org) to make a status page (all I needed was to check status code by sending get request to services).
When launcher checks Mojang statuses, it will check ids that I added in mojang.js. You can get theses ids from [there](https://github.com/GeekCornerGH/helios-status-page/tree/master/api). It will check the uptime.json file, and that's all.

~~Ah yeah also there is a [web ui](https://geekcornergh.github.io/helios-status-page) avaliable~~

Have a good day

### CODE REVIEW

**Comment by dscalzi** [comment]
Needs to be refactored into https://github.com/dscalzi/helios-core/blob/master/lib/mojang/rest/MojangRestAPI.ts#L78
I also either need write access to https://github.com/GeekCornerGH/helios-status-page or we move it to an org. Up to you

**Comment by GeekCornerGH** [comment]
We can move to an org sure

**Comment by SirOMGitsYOU** [comment]
Has there been any movement on refactoring the above resolution into Helios-Core as currently still showing broken as everything showing offline.

**Comment by GeekCornerGH** [comment]
@dscalzi bump x)

**Comment by toster234** [comment]
@GeekCornerGH maybe an update would be useful. Since November 2022 there is downtage.

**Pull request closed without merging**
